spring:
  application:
    name: user-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 60000

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

logging:
  file.name: logs/log.log
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
    org.springframework: warn
    org.springframework.cache: trace
